# Generated by Django 5.2.4 on 2025-07-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_provider_id', models.TextField(choices=[('OPENAI', 'OpenAI'), ('OLLAMA', 'Ollama (Local LLM server)')])),
                ('model_name', models.TextField(default='gpt-4.1-mini')),
                ('api_key', models.CharField(default='ollama')),
                ('base_url', models.URLField(default=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
