# Generated by Django 5.2.4 on 2025-07-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0002_alter_providermodel_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='model_provider_id',
            field=models.TextField(choices=[('OPENAI', 'OpenAI'), ('OLLAMA', 'Ollama (Local LLM server)')], primary_key=True, serialize=False),
        ),
    ]
