# Generated by Django 5.2.4 on 2025-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0003_remove_providermodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='base_url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
