# Generated by Django 5.2.4 on 2025-07-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0004_alter_providermodel_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='model_name',
            field=models.CharField(default='gpt-4.1-mini'),
        ),
    ]
