# Generated by Django 5.2.4 on 2025-07-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0005_alter_providermodel_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_webapp.providermodel')),
            ],
        ),
    ]
