# Generated by Django 5.2.4 on 2025-07-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0006_selectionparam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providermodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='selectionparam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
