# Generated by Django 5.2.4 on 2025-07-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0007_remove_providermodel_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None)),
                ('base_url', models.URLField(default='http://127.0.0.1:8000')),
                ('connection_type', models.CharField(choices=[('sse', 'Sse'), ('http', 'Http'), ('STREAM', 'Streamable http')], default='sse')),
            ],
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='model_provider_id',
            field=models.TextField(choices=[('OPENAI', 'OpenAI'), ('OLLAMA', 'Ollama (Private LLM server)'), ('ANTHROPIC', 'Anthropic')], primary_key=True, serialize=False),
        ),
    ]
