# Generated by Django 5.2.4 on 2025-07-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0008_mcpserverconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserverconfig',
            name='connection_type',
            field=models.CharField(choices=[('sse', 'Sse')], default='sse'),
        ),
    ]
