# Generated by Django 5.2.4 on 2025-07-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0009_alter_mcpserverconfig_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermodel',
            name='is_active',
            field=models.BooleanField(default=None, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='SelectionParam',
        ),
    ]
