# Generated by Django 5.2.4 on 2025-07-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0010_providermodel_is_active_delete_selectionparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (None, 'No')], default=None, null=True, unique=True),
        ),
    ]
