# Generated by Django 5.2.4 on 2025-07-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_webapp', '0012_alter_providermodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
